<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/09/26 10:19:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
