<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/10/03 15:46:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'password',
  'name' => 'doctrine',
)),);
